# Generated by Django 4.0.5 on 2022-06-23 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskBoard',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Tasks.basemodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskboard_project', to='Tasks.project')),
            ],
            bases=('Tasks.basemodel',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Tasks.basemodel')),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='TODO', max_length=15)),
                ('task_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_taskboard', to='Tasks.taskboard')),
            ],
            bases=('Tasks.basemodel',),
        ),
    ]
